### ISSUE TITLE
"What's New" Category: Posts too wide on desktop

### ISSUE THREAD

**Issue by bytesource** [unisonweb/website#56]
Hi, 

I noticed that the body text on posts in the "What's New" don't have a max-length set and are therefore difficult to read on desktop. 

Example page: https://www.unison-lang.org/whats-new/unison-services-preview/

Maybe you could do something like this:

``` css
.unison-doc {
  max-width: 700px;
  margin: 0 auto;
}
```

Keep up the good work!

Stefan
